receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp_http/tempo:
    endpoint: http://tempo:4318
  debug:
    verbosity: detailed
    sampling_initial: 100
    sampling_thereafter: 1

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp_http/tempo]
